DECLARE @S1 VARCHAR (50) = /*<SOURCECODE1>*/'19SEPAQ'/*</SOURCECODE1>*/;
-- ----------------------------------------------------------------------------------------------------
WITH
-- ----------------------------------------------------------------------------------------------------
cte_payments as (
  SELECT
    B1.SERIALNUMBER, B1.SOURCECODE, S1.SOURCETYPE, B2.DATEOFPAYMENT, B1.PAYMENTAMOUNT, B1.GSTAMOUNT, B1.PAYMENTAMOUNTNETT
    ,B3.PLEDGEID ,B2.REVERSED
    , YEAR(B2.DATEOFPAYMENT) + CASE WHEN MONTH(B2.DATEOFPAYMENT) < 7 THEN 0 ELSE 1 END AS [PAYMENT_FY]
    , CASE WHEN B2.REVERSED IN (-1, 1, 2)
      THEN 0
      ELSE DENSE_RANK() OVER (PARTITION BY CASE WHEN B2.REVERSED IN (1, -1, 2) THEN 0 ELSE -1 END ORDER BY CONCAT(CONVERT(VARCHAR(10), B2.DATEOFPAYMENT, 112), B2.SERIALNUMBER, B2.ADMITNAME, B2.RECEIPTNO) ASC)
      END AS [TRXID]
  FROM
    TBL_BATCHITEMSPLIT            B1
    LEFT JOIN TBL_BATCHITEM       B2 ON (B1.SERIALNUMBER = B2.SERIALNUMBER) AND (B1.RECEIPTNO = B2.RECEIPTNO) AND (B1.ADMITNAME = B2.ADMITNAME)
    LEFT JOIN TBL_BATCHITEMPLEDGE B3 ON (B1.SERIALNUMBER = B3.SERIALNUMBER) AND (B1.RECEIPTNO = B3.RECEIPTNO) AND (B1.ADMITNAME = B3.ADMITNAME) AND (B1.LINEID = B3.LINEID)
    LEFT JOIN TBL_PLEDGEHEADER    P1 ON (B3.PLEDGEID = P1.PLEDGEID)
    LEFT JOIN TBL_BATCHHEADER     B4 ON (B2.ADMITNAME = B4.ADMITNAME)
    LEFT JOIN Tbl_SOURCECODE      S1 ON (B1.SOURCECODE = S1.SOURCECODE)
  WHERE
    (B2.REVERSED IS NULL OR NOT(B2.REVERSED IN (1, -1))) AND (B4.STAGE ='Batch Approved')
    AND B1.SOURCECODE = @S1
)
-- ----------------------------------------------------------------------------------------------------
,cte_first_date as (
  SELECT SERIALNUMBER, MIN(DATEOFPAYMENT) AS [FIRSTDATE], YEAR(MIN(DATEOFPAYMENT)) + CASE WHEN MONTH(MIN(DATEOFPAYMENT)) < 7 THEN 0 ELSE 1 END AS [FIRSTFY]
  FROM TBL_BATCHITEM
  WHERE (REVERSED IS NULL OR REVERSED NOT IN (-1, 1, 2))
  GROUP BY SERIALNUMBER
  HAVING SERIALNUMBER IN (SELECT [SERIALNUMBER] FROM TBL_BATCHITEMSPLIT WHERE [SOURCECODE] = @S1 GROUP BY [SERIALNUMBER])
)
-- ----------------------------------------------------------------------------------------------------
SELECT
  t1.SOURCECODE
  , MAX(t1.TRXID) AS [TRANSACTIONS]
  , COUNT(DISTINCT CASE WHEN t1.SOURCETYPE LIKE '%SPONSORSHIP%' THEN t1.PLEDGEID ELSE NULL END) AS [PLEDGES]
  , COUNT(DISTINCT CASE WHEN t1.REVERSED IN (1, -1, 2) THEN NULL ELSE t1.SERIALNUMBER END) AS [CONTACTS]
  , SUM(t1.PAYMENTAMOUNT) AS [TOTAL]
  , SUM(t1.GSTAMOUNT) AS [GST]
  , SUM(t1.PAYMENTAMOUNTNETT) AS [NET]
  , COUNT(DISTINCT
      CASE WHEN  t2.FIRSTDATE = t1.DATEOFPAYMENT AND (t1.REVERSED IS NULL OR NOT(t1.REVERSED IN (1, -1, 2)))
      THEN t1.SERIALNUMBER
      ELSE NULL
      END
    ) AS [NEW_CONTACTS]
FROM
  cte_payments t1
  left join cte_first_date t2 on (t1.SERIALNUMBER = t2.SERIALNUMBER)
GROUP BY
  t1.SOURCECODE