SELECT STUFF((
  SELECT ',' + [SOURCECODE]
  FROM (
    SELECT B1.SOURCECODE, B2.REVERSED
      ,CASE WHEN B2.REVERSED = 2
        THEN 0
        ELSE DENSE_RANK() OVER (PARTITION BY CASE WHEN B2.REVERSED IN (1, -1, 2) THEN 0 ELSE -1 END ORDER BY CONCAT(CONVERT(VARCHAR(10), B2.DATEOFPAYMENT, 112), B2.SERIALNUMBER) ASC)
        END AS [TRXID]
    FROM
      TBL_BATCHITEMSPLIT        B1
      LEFT JOIN TBL_BATCHITEM   B2 ON (B1.SERIALNUMBER = B2.SERIALNUMBER) AND (B1.RECEIPTNO = B2.RECEIPTNO) AND (B1.ADMITNAME = B2.ADMITNAME)
      LEFT JOIN TBL_BATCHHEADER B4 ON (B2.ADMITNAME = B4.ADMITNAME)
    WHERE
      (B2.REVERSED IS NULL OR NOT (B2.REVERSED=1 OR B2.REVERSED=-1 OR B2.REVERSED=2)) -- Full reversal and re-entry should be excluded all time
      AND (B4.STAGE ='Batch Approved')
      AND B1.SERIALNUMBER = ?
      AND B2.DATEOFPAYMENT BETWEEN ? AND CURRENT_TIMESTAMP
    ) tmp
    WHERE [TRXID] = 1
  FOR XML PATH('')
), 1, 1, '') AS [FIRSTDATE_SOURCECODES]