select
  CASE WHEN (D1.FISHING_HARD_FIRST_DATEOFPAYMENT) IS NULL
  THEN -- NG
    CASE WHEN C1.CONTACT_CREATED IS NULL OR DATEDIFF(day, C1.CONTACT_CREATED, @FISHINGPOOL_DATE1) < 0
    THEN 'NoE (1)'
    ELSE
      CASE WHEN DATEDIFF(month, C1.CONTACT_CREATED, @FISHINGPOOL_DATE1) < 12
      THEN 'NG1 (1)'
      ELSE
        CASE WHEN DATEDIFF(month, C1.CONTACT_CREATED, @FISHINGPOOL_DATE1) < 24
        THEN 'NG2 (1)'
        ELSE
          CASE WHEN DATEDIFF(month, C1.CONTACT_CREATED, @FISHINGPOOL_DATE1) < 60
          THEN 'NG3 (1)'
          ELSE 'NG4 (1)'
          END
        END
      END
    END
  ELSE -- Gaver
    CASE WHEN (D1.ACTIVE_IN_ANCHOR_FY_MINUS0) = -1
    THEN -- Active
      CASE WHEN (D1.ACTIVE_IN_ANCHOR_FY_MINUS1) = -1
      THEN
        CASE  WHEN (D1.ACTIVE_IN_ANCHOR_FY_MINUS2) = -1
        THEN '_MULTI (1)'
        ELSE
          CASE WHEN (D1.FISHING_HARD_FIRST_DATEOFPAYMENT_FY) = (D1.ANCHOR_FY) -1
          THEN '_2NEW (1)'
          ELSE '_2REC (1)'
          END
        END
      ELSE
        CASE WHEN (D1.FISHING_HARD_FIRST_DATEOFPAYMENT_FY) = (D1.ANCHOR_FY)
        THEN '_1NEW (1)'
        ELSE '_1REC (1)'
        END
      END
    ELSE  --Lapsed
      CASE WHEN DATEDIFF(month, (D1.FISHING_HARD_LAST_DATEOFPAYMENT), @FISHINGPOOL_DATE1) <= 12
      THEN 'LPS1 (1)'
      ELSE
        CASE WHEN DATEDIFF(month, (D1.FISHING_HARD_LAST_DATEOFPAYMENT), @FISHINGPOOL_DATE1) <= 24
        THEN 'LPS2 (1)'
        ELSE
          CASE WHEN DATEDIFF(month, (D1.FISHING_HARD_LAST_DATEOFPAYMENT), @FISHINGPOOL_DATE1) < 60
          THEN 'LPS3 (1)'
          ELSE 'LPS4 (1)'
          END
        END
      END
    END
  END AS [from],

  CASE WHEN (D2.FISHING_HARD_FIRST_DATEOFPAYMENT) IS NULL OR DATEDIFF(day, C1.CONTACT_CREATED, @FISHINGPOOL_DATE2) < 0
  THEN
    CASE WHEN C1.CONTACT_CREATED IS NULL
    THEN 'NoE (2)'
    ELSE
      CASE WHEN DATEDIFF(month, C1.CONTACT_CREATED, @FISHINGPOOL_DATE2) < 12
      THEN 'NG1 (2)'
      ELSE
        CASE WHEN DATEDIFF(month, C1.CONTACT_CREATED, @FISHINGPOOL_DATE2) < 24
        THEN 'NG2 (2)'
        ELSE
          CASE WHEN DATEDIFF(month, C1.CONTACT_CREATED, @FISHINGPOOL_DATE2) < 60
          THEN 'NG3 (2)'
          ELSE 'NG4 (2)'
          END
        END
      END
    END
  ELSE
    CASE WHEN (D2.ACTIVE_IN_ANCHOR_FY_MINUS0) = -1
    THEN
      CASE WHEN (D2.ACTIVE_IN_ANCHOR_FY_MINUS1) = -1
      THEN
        CASE  WHEN (D2.ACTIVE_IN_ANCHOR_FY_MINUS2) = -1
        THEN '_MULTI (2)'
        ELSE
          CASE WHEN (D2.FISHING_HARD_FIRST_DATEOFPAYMENT_FY) = (D2.ANCHOR_FY) -1
          THEN '_2NEW (2)'
          ELSE '_2REC (2)'
          END
        END
      ELSE
        CASE WHEN (D2.FISHING_HARD_FIRST_DATEOFPAYMENT_FY) = (D2.ANCHOR_FY)
        THEN '_1NEW (2)'
        ELSE '_1REC (2)'
        END
      END
    ELSE
      CASE WHEN DATEDIFF(month, (D2.FISHING_HARD_LAST_DATEOFPAYMENT), @FISHINGPOOL_DATE2) <= 12
      THEN 'LPS1 (2)'
      ELSE
        CASE WHEN DATEDIFF(month, (D2.FISHING_HARD_LAST_DATEOFPAYMENT), @FISHINGPOOL_DATE2) <= 24
        THEN 'LPS2 (2)'
        ELSE
          CASE WHEN DATEDIFF(month, (D2.FISHING_HARD_LAST_DATEOFPAYMENT), @FISHINGPOOL_DATE2) < 60
          THEN 'LPS3 (2)'
          ELSE 'LPS4 (2)'
          END
        END
      END
    END
  END AS [to],

  COUNT(C1.SN) AS [weight]

  -- , CASE WHEN (D3.FISHING_SOFT_FIRST_DATEOFPAYMENT) IS NULL THEN 0 ELSE -1 END AS [FILTER_ANCHOR1_SOFT]
  -- , CASE WHEN (D4.FISHING_SOFT_FIRST_DATEOFPAYMENT) IS NULL THEN 0 ELSE -1 END AS [FILTER_ANCHOR2_SOFT]
from
  cte_contacts C1
  left join cte_fishing1_hard_payment_date D1 on (C1.SN = D1.SERIALNUMBER)
  left join cte_fishing2_hard_payment_date D2 on (C1.SN = D2.SERIALNUMBER)
  left join cte_fishing1_soft_payment_date D3 on (C1.SN = D3.SN_SOFT)
  left join cte_fishing2_soft_payment_date D4 on (C1.SN = D4.SN_SOFT)

group by
  CASE WHEN (D1.FISHING_HARD_FIRST_DATEOFPAYMENT) IS NULL
  THEN -- NG
    CASE WHEN C1.CONTACT_CREATED IS NULL OR DATEDIFF(day, C1.CONTACT_CREATED, @FISHINGPOOL_DATE1) < 0
    THEN 'NoE (1)'
    ELSE
      CASE WHEN DATEDIFF(month, C1.CONTACT_CREATED, @FISHINGPOOL_DATE1) < 12
      THEN 'NG1 (1)'
      ELSE
        CASE WHEN DATEDIFF(month, C1.CONTACT_CREATED, @FISHINGPOOL_DATE1) < 24
        THEN 'NG2 (1)'
        ELSE
          CASE WHEN DATEDIFF(month, C1.CONTACT_CREATED, @FISHINGPOOL_DATE1) < 60
          THEN 'NG3 (1)'
          ELSE 'NG4 (1)'
          END
        END
      END
    END
  ELSE -- Gaver
    CASE WHEN (D1.ACTIVE_IN_ANCHOR_FY_MINUS0) = -1
    THEN -- Active
      CASE WHEN (D1.ACTIVE_IN_ANCHOR_FY_MINUS1) = -1
      THEN
        CASE  WHEN (D1.ACTIVE_IN_ANCHOR_FY_MINUS2) = -1
        THEN '_MULTI (1)'
        ELSE
          CASE WHEN (D1.FISHING_HARD_FIRST_DATEOFPAYMENT_FY) = (D1.ANCHOR_FY) -1
          THEN '_2NEW (1)'
          ELSE '_2REC (1)'
          END
        END
      ELSE
        CASE WHEN (D1.FISHING_HARD_FIRST_DATEOFPAYMENT_FY) = (D1.ANCHOR_FY)
        THEN '_1NEW (1)'
        ELSE '_1REC (1)'
        END
      END
    ELSE  --Lapsed
      CASE WHEN DATEDIFF(month, (D1.FISHING_HARD_LAST_DATEOFPAYMENT), @FISHINGPOOL_DATE1) <= 12
      THEN 'LPS1 (1)'
      ELSE
        CASE WHEN DATEDIFF(month, (D1.FISHING_HARD_LAST_DATEOFPAYMENT), @FISHINGPOOL_DATE1) <= 24
        THEN 'LPS2 (1)'
        ELSE
          CASE WHEN DATEDIFF(month, (D1.FISHING_HARD_LAST_DATEOFPAYMENT), @FISHINGPOOL_DATE1) < 60
          THEN 'LPS3 (1)'
          ELSE 'LPS4 (1)'
          END
        END
      END
    END
  END,

  CASE WHEN (D2.FISHING_HARD_FIRST_DATEOFPAYMENT) IS NULL OR DATEDIFF(day, C1.CONTACT_CREATED, @FISHINGPOOL_DATE2) < 0
  THEN
    CASE WHEN C1.CONTACT_CREATED IS NULL
    THEN 'NoE (2)'
    ELSE
      CASE WHEN DATEDIFF(month, C1.CONTACT_CREATED, @FISHINGPOOL_DATE2) < 12
      THEN 'NG1 (2)'
      ELSE
        CASE WHEN DATEDIFF(month, C1.CONTACT_CREATED, @FISHINGPOOL_DATE2) < 24
        THEN 'NG2 (2)'
        ELSE
          CASE WHEN DATEDIFF(month, C1.CONTACT_CREATED, @FISHINGPOOL_DATE2) < 60
          THEN 'NG3 (2)'
          ELSE 'NG4 (2)'
          END
        END
      END
    END
  ELSE
    CASE WHEN (D2.ACTIVE_IN_ANCHOR_FY_MINUS0) = -1
    THEN
      CASE WHEN (D2.ACTIVE_IN_ANCHOR_FY_MINUS1) = -1
      THEN
        CASE  WHEN (D2.ACTIVE_IN_ANCHOR_FY_MINUS2) = -1
        THEN '_MULTI (2)'
        ELSE
          CASE WHEN (D2.FISHING_HARD_FIRST_DATEOFPAYMENT_FY) = (D2.ANCHOR_FY) -1
          THEN '_2NEW (2)'
          ELSE '_2REC (2)'
          END
        END
      ELSE
        CASE WHEN (D2.FISHING_HARD_FIRST_DATEOFPAYMENT_FY) = (D2.ANCHOR_FY)
        THEN '_1NEW (2)'
        ELSE '_1REC (2)'
        END
      END
    ELSE
      CASE WHEN DATEDIFF(month, (D2.FISHING_HARD_LAST_DATEOFPAYMENT), @FISHINGPOOL_DATE2) <= 12
      THEN 'LPS1 (2)'
      ELSE
        CASE WHEN DATEDIFF(month, (D2.FISHING_HARD_LAST_DATEOFPAYMENT), @FISHINGPOOL_DATE2) <= 24
        THEN 'LPS2 (2)'
        ELSE
          CASE WHEN DATEDIFF(month, (D2.FISHING_HARD_LAST_DATEOFPAYMENT), @FISHINGPOOL_DATE2) < 60
          THEN 'LPS3 (2)'
          ELSE 'LPS4 (2)'
          END
        END
      END
    END
  END

  -- , CASE WHEN (D3.FISHING_SOFT_FIRST_DATEOFPAYMENT) IS NULL THEN 0 ELSE -1 END
  -- , CASE WHEN (D4.FISHING_SOFT_FIRST_DATEOFPAYMENT) IS NULL THEN 0 ELSE -1 END
order by
  [from], [to]