select
  ACTIVITY_CODE
  , SERIALNUMBER
  -- , CASE WHEN SOURCETYPE = 'Merchandise Purchase' OR SOURCETYPE = 'Merchandise Postage' THEN 'Merchandise P&P' ELSE SOURCETYPE END  AS [SOURCETYPE]
  , SUM(PAYMENTAMOUNTNETT) AS [PAYMENTAMOUNTNETT]
  , SUM(PAYMENTAMOUNT) AS [PAYMENTAMOUNT]
  , SUM(GSTAMOUNT) AS [GSTAMOUNT]

  , SUM(CASE WHEN SOURCETYPE = 'Merchandise Purchase' OR SOURCETYPE = 'Merchandise Postage' OR SOURCETYPE = 'Merchgulpandise' THEN PAYMENTAMOUNTNETT ELSE NULL END) AS [MP&P]
  , SUM(CASE WHEN SOURCETYPE = 'Merchandise Donation' THEN PAYMENTAMOUNTNETT ELSE NULL END) AS [MDON]
  , SUM(CASE WHEN SOURCETYPE = 'Merchandise Gift of Love' THEN PAYMENTAMOUNTNETT ELSE NULL END) AS [MGOL]
  , SUM(CASE WHEN SOURCETYPE = 'Merchandise Sponsorship' THEN PAYMENTAMOUNTNETT ELSE NULL END) AS [MSPN]

  , CONCAT(
    CASE WHEN SUM(CASE WHEN SOURCETYPE = 'Merchandise Purchase' OR SOURCETYPE = 'Merchandise Postage' THEN PAYMENTAMOUNTNETT ELSE NULL END) > 0
    THEN 'P' ELSE NULL END,
    CASE WHEN SUM(CASE WHEN SOURCETYPE = 'Merchandise Donation' THEN PAYMENTAMOUNTNETT ELSE NULL END) > 0
    THEN 'D' ELSE NULL END,
    CASE WHEN SUM(CASE WHEN SOURCETYPE = 'Merchandise Gift of Love' THEN PAYMENTAMOUNTNETT ELSE NULL END) > 0
    THEN 'G' ELSE NULL END,
    CASE WHEN SUM(CASE WHEN SOURCETYPE = 'Merchandise Sponsorship' THEN PAYMENTAMOUNTNETT ELSE NULL END) > 0
    THEN 'S' ELSE NULL END
  ) AS [MCOMBINE]

from
   cte_payments
where
  ISMRECH IN (-1)
group by
  ACTIVITY_CODE
  -- , CASE WHEN SOURCETYPE = 'Merchandise Purchase' OR SOURCETYPE = 'Merchandise Postage' THEN 'Merchandise P&P' ELSE SOURCETYPE END
  , SERIALNUMBER
order by
  ACTIVITY_CODE
  , SERIALNUMBER