select
  C1.SN, C1.CONTACT_CREATED
--   , DATEADD(d, 1 , @FISHINGPOOL_DATE2) AS [ANCHOR]
  -- , YEAR(@FISHINGPOOL_DATE2) + CASE WHEN MONTH(@FISHINGPOOL_DATE2) < 7 THEN 1 ELSE 0 END AS [ANCHOR_FY]
  , MIN(pmt.DATEOFPAYMENT) AS [FIRST_PAYMENTDATE]
  , MAX(pmt.DATEOFPAYMENT) AS [LAST_PAYMENTDATE]
  , CASE WHEN YEAR(MAX(pmt.DATEOFPAYMENT)) + CASE WHEN MONTH(MAX(pmt.DATEOFPAYMENT)) < 7 THEN 1 ELSE 0 END = YEAR(@FISHINGPOOL_DATE2) + CASE WHEN MONTH(@FISHINGPOOL_DATE2) < 7 THEN 1 ELSE 0 END
    THEN -1 ELSE 0 END AS [FILTER_ACTIVE]


  , C1.CONTACTTYPE, C1.PRIMARYCATEGORY, C1.SOURCE, C1.GENDER, C1.AGE
  , C1.GENERATION, C1.GENERATION_ABBREVATION
  , C1.STATE, C1.COUNTRY, C1.POSTCODE
  , C1.DONOTMAILREASON
  , C1.FILTER_MAJDONOR
  , C1.FILTER_ANONYMOUS
  , C1.FILTER_DONOTMAIL
  , C1.FILTER_DECEASED
  , C1.FILTER_ESTATE
  , C1.FILTER_DONOTCALL
  , C1.FILTER_EMAIL
  , C1.FILTER_TWITTER
  , C1.FILTER_FACEBOOK
  , C1.FILTER_LINKEDIN
  , C1.FILTER_PHONENUMBER
from
  cte_contacts C1
  left join cte_payments pmt on (C1.SN = pmt.SERIALNUMBER)
-- where
--   C1.CONTACT_CREATED < DATEADD(d, 1 , @FISHINGPOOL_DATE2)
--   OR pmt.DATEOFPAYMENT < DATEADD(d, 1 , @FISHINGPOOL_DATE2)
group by 
  C1.SN, C1.CONTACT_CREATED
  , C1.CONTACTTYPE, C1.PRIMARYCATEGORY, C1.SOURCE, C1.GENDER, C1.AGE
  , C1.GENERATION, C1.GENERATION_ABBREVATION
  , C1.STATE, C1.COUNTRY, C1.POSTCODE
  , C1.DONOTMAILREASON
  , C1.FILTER_MAJDONOR
  , C1.FILTER_ANONYMOUS
  , C1.FILTER_DONOTMAIL
  , C1.FILTER_DECEASED
  , C1.FILTER_ESTATE
  , C1.FILTER_DONOTCALL
  , C1.FILTER_EMAIL
  , C1.FILTER_TWITTER
  , C1.FILTER_FACEBOOK
  , C1.FILTER_LINKEDIN
  , C1.FILTER_PHONENUMBER