SELECT
  DISTINCT [FY] = YEAR(T1.CREATED) + IIF(MONTH(T1.CREATED)<7,0,1)
FROM
  dbo.TBL_PLEDGEHEADER T1
WHERE
  (RTRIM(ISNULL(T1.EXTERNALREF,''))='') AND (RTRIM(ISNULL(T1.EXTERNALREFTYPE,''))='')
ORDER BY
  [FY] ASC
