DECLARE @UNSOLICITED varchar(25) = '____.Unsolicited';
SELECT
  DISTINCT
  CASE WHEN S1.ADDITIONALCODE3 IS NULL OR RTRIM(S1.ADDITIONALCODE3) = '' OR S1.ADDITIONALCODE3 LIKE '%Unsolicited%'
  THEN
    CASE WHEN S1.SOURCETYPE LIKE '%Sponsorship'
    THEN
      CASE WHEN P1.RECRUITMENTMETHOD IS NULL OR P1.RECRUITMENTMETHOD LIKE '%Unsolicited%'
      THEN @UNSOLICITED
      ELSE P1.RECRUITMENTMETHOD
      END
    ELSE @UNSOLICITED
    END
  ELSE S1.ADDITIONALCODE3
  END AS [CAMPAIGNCODE]
FROM
    TBL_BATCHITEMSPLIT            B1
    LEFT JOIN TBL_BATCHITEM       B2 ON (B1.SERIALNUMBER = B2.SERIALNUMBER) AND (B1.RECEIPTNO = B2.RECEIPTNO) AND (B1.ADMITNAME = B2.ADMITNAME)
    LEFT JOIN TBL_BATCHITEMPLEDGE B3 ON (B1.SERIALNUMBER = B3.SERIALNUMBER) AND (B1.RECEIPTNO = B3.RECEIPTNO) AND (B1.ADMITNAME = B3.ADMITNAME) AND (B1.LINEID = B3.LINEID)
    LEFT JOIN TBL_PLEDGEHEADER    P1 ON (B3.PLEDGEID = P1.PLEDGEID)
    LEFT JOIN TBL_BATCHHEADER     B4 ON (B2.ADMITNAME = B4.ADMITNAME)
    LEFT JOIN Tbl_SOURCECODE      S1 ON (B1.SOURCECODE = S1.SOURCECODE)
WHERE
    (B2.REVERSED IS NULL OR NOT(B2.REVERSED IN (1, -1))) AND (B4.STAGE ='Batch Approved')
    AND B2.DATEOFPAYMENT BETWEEN ? AND ?