SELECT
  DISTINCT [FY] = YEAR(T1.DATEOFPAYMENT) + IIF(MONTH(T1.DATEOFPAYMENT)<7,0,1)
FROM
  dbo.TBL_BATCHITEM T1
  INNER JOIN dbo.TBL_BATCHITEMSPLIT T2 ON (T1.ADMITNAME = T2.ADMITNAME AND T1.RECEIPTNO = T2.RECEIPTNO AND T1.SERIALNUMBER = T2.SERIALNUMBER)
  INNER JOIN dbo.TBL_SOURCECODE S1 ON (T2.SOURCECODE = S1.SOURCECODE )
WHERE
  (T1.REVERSED IS NULL OR NOT (T1.REVERSED = -1 OR T1.REVERSED =1 OR T1.REVERSED =2))
  AND (S1.SOURCETYPE LIKE '%SPONSORSHIP%')
ORDER BY
  [FY] ASC