WITH
cte_merch_payments as (
SELECT
  B1.SERIALNUMBER
  , MERCH=IIF(S1.SOURCETYPE LIKE 'MERCH%',-1,0)
  , B2.DATEOFPAYMENT
  , B2.MANUALRECEIPTNO
  , FIRSTDATE=FIRST_VALUE(B2.DATEOFPAYMENT) OVER (PARTITION BY B1.SERIALNUMBER ORDER BY DATEOFPAYMENT ASC)
  , FIRSTFY=(YEAR(FIRST_VALUE(B2.DATEOFPAYMENT) OVER (PARTITION BY B1.SERIALNUMBER ORDER BY DATEOFPAYMENT ASC))+IIF(MONTH(FIRST_VALUE(B2.DATEOFPAYMENT) OVER (PARTITION BY B1.SERIALNUMBER ORDER BY DATEOFPAYMENT ASC))<7,0,1))
  , FIRSTMONTH = MONTH(FIRST_VALUE(B2.DATEOFPAYMENT) OVER (PARTITION BY B1.SERIALNUMBER ORDER BY DATEOFPAYMENT ASC))
FROM
  TBL_BATCHITEMSPLIT        B1
  LEFT JOIN TBL_BATCHITEM   B2 ON (B1.SERIALNUMBER = B2.SERIALNUMBER) AND (B1.RECEIPTNO = B2.RECEIPTNO) AND (B1.ADMITNAME = B2.ADMITNAME)
  LEFT JOIN TBL_BATCHHEADER B4 ON (B2.ADMITNAME = B4.ADMITNAME)
  LEFT JOIN TBL_SOURCECODE  S1 ON (B1.SOURCECODE = S1.SOURCECODE)
WHERE
  (B2.REVERSED IS NULL OR NOT (B2.REVERSED=1 OR B2.REVERSED=-1 OR B2.REVERSED=2)) -- Full reversal and re-entry should be excluded all time
  AND (B4.STAGE ='Batch Approved')
)
-- --------------------------------------------------------------
select SERIALNUMBER
  , FIRSTDATE
  , FIRSTORDER=MIN(MANUALRECEIPTNO)
from cte_merch_payments
where 
  MERCH = -1 AND DATEOFPAYMENT = FIRSTDATE
  AND FIRSTDATE BETWEEN ? AND ?
group by 
  SERIALNUMBER, FIRSTDATE
order by
  FIRSTDATE desc