WITH
-- --------------------------------------------------------------
cet_mysourcecode AS (
  SELECT SOURCECODE,SOURCETYPE
    , CAST(ADDITIONALCODE1 AS VARCHAR(10)) AS ACCOUNT
    , CAST(ADDITIONALCODE5  AS VARCHAR(5)) AS CLASS
    , ADDITIONALCODE3 AS CAMPAIGN
  	,IIF(SOURCETYPE LIKE 'Merch%', 'Merchandise Platform','Non-Merchandise Platform') AS PLATFORM
  	,IIF(RTRIM(ISNULL(ADDITIONALCODE3,'')) = '', 'Unsolicited','Solicited') AS SOLICIT
  	,IIF(SOURCETYPE LIKE 'Bequest', 'Bequest'
      ,IIF(SOURCETYPE LIKE '%Sponsorship%', 'Pledge'
	    ,IIF(SOURCETYPE LIKE 'Merch%Purchase%' OR SOURCETYPE LIKE 'Merch%Postage%', 'Purchase&Postage'
	    ,IIF(SOURCETYPE LIKE 'Group', 'Group'
          ,'Donation')))) AS TQTYPE
  FROM TBL_SOURCECODE
)
-- --------------------------------------------------------------
,cte_sankey_attributes AS (
  SELECT
    SUM(B1.PAYMENTAMOUNT) AS TOTAL
    ,S1.SOLICIT ,S1.PLATFORM ,S1.TQTYPE ,ISNULL(B1.DESTINATIONCODE, 'BLANK') AS DESTINATIONCODE, ISNULL(B1.DESTINATIONCODE2, 'BLANK') AS DESTINATIONCODE2
  FROM
    TBL_BATCHITEMSPLIT        B1
    LEFT JOIN TBL_BATCHITEM   B2 ON (B1.SERIALNUMBER = B2.SERIALNUMBER) AND (B1.RECEIPTNO = B2.RECEIPTNO) AND (B1.ADMITNAME = B2.ADMITNAME)
    LEFT JOIN TBL_BATCHHEADER B4 ON (B2.ADMITNAME = B4.ADMITNAME)
    LEFT JOIN cet_mysourcecode   S1 ON (B1.SOURCECODE = S1.SOURCECODE)
  WHERE
    (B2.REVERSED IS NULL OR NOT(B2.REVERSED=1 OR B2.REVERSED=-1)) AND (B4.STAGE ='Batch Approved')
    AND B2.DATEOFPAYMENT
    	BETWEEN DATEFROMPARTS(IIF(MONTH(CURRENT_TIMESTAMP)<7,YEAR(CURRENT_TIMESTAMP)-1,YEAR(CURRENT_TIMESTAMP)),7,1)
		  AND DATEFROMPARTS(IIF(MONTH(CURRENT_TIMESTAMP)<7,YEAR(CURRENT_TIMESTAMP),YEAR(CURRENT_TIMESTAMP)+1),6,30)
  GROUP BY
    S1.SOLICIT ,S1.PLATFORM ,S1.TQTYPE ,B1.DESTINATIONCODE, B1.DESTINATIONCODE2
)
-- --------------------------------------------------------------
, cte_sankey AS (
  SELECT SUM(TOTAL) AS TOTAL, SOLICIT AS ATTR1, PLATFORM AS ATTR2
  FROM cte_sankey_attributes
  GROUP BY SOLICIT, PLATFORM
  UNION
  SELECT SUM(TOTAL) AS TOTAL, PLATFORM AS ATTR1, TQTYPE AS ATTR2
  FROM cte_sankey_attributes
  GROUP BY PLATFORM, TQTYPE
--   UNION
--   SELECT SUM(TOTAL) AS TOTAL, TQTYPE AS ATTR1, DESTINATIONCODE AS ATTR2
--   FROM cte_sankey_attributes
--   GROUP BY TQTYPE, DESTINATIONCODE
)
-- --------------------------------------------------------------
select
  *
from
  cte_sankey

