DECLARE @FYOFFSET AS INT, @CFY AS INT,  @FY AS INT, @BLANK AS VARCHAR(7);
SET @CFY=YEAR(CURRENT_TIMESTAMP)+IIF(MONTH(CURRENT_TIMESTAMP)<7,0,1);
SET @FY=/*<FY>*/2019/*</FY>*/;  -- FY should be bigger than 1
SET @BLANK=/*<BLANK_STR>*/':BLANK'/*</BLANK_STR>*/;

WITH
-- --------------------------------------------------------------
cte_pledge_source as (
  SELECT TBL_PLEDGEDESTINATION.PLEDGEID
    ,[SOURCECODES]=COUNT(TBL_PLEDGEDESTINATION.SOURCECODE)
    ,[FIRST_SOURCECODE1]=IIF(RTRIM(ISNULL(MIN(TBL_PLEDGEDESTINATION.SOURCECODE),''))='',@BLANK, MIN(TBL_PLEDGEDESTINATION.SOURCECODE))
    ,[FIRST_SOURCECODE2]=IIF(RTRIM(ISNULL(MIN(TBL_PLEDGEDESTINATION.SOURCECODE2),''))='',@BLANK, MIN(TBL_PLEDGEDESTINATION.SOURCECODE2))
    ,[FIRST_DESTINATION1]=IIF(RTRIM(ISNULL(MIN(TBL_PLEDGEDESTINATION.DESTINATIONCODE),''))='',@BLANK, MIN(TBL_PLEDGEDESTINATION.DESTINATIONCODE))
    ,[FIRST_DESTINATION2]=IIF(RTRIM(ISNULL(MIN(TBL_PLEDGEDESTINATION.DESTINATIONCODE2),''))='',@BLANK, MIN(TBL_PLEDGEDESTINATION.DESTINATIONCODE2))
  FROM TBL_PLEDGEDESTINATION
  GROUP BY PLEDGEID
)
-- --------------------------------------------------------------
, cte_pledge_sourcetype as (
  SELECT
    cps.*, TBL_SOURCECODE.SOURCETYPE
  FROM cte_pledge_source cps LEFT JOIN TBL_SOURCECODE ON (cps.FIRST_SOURCECODE1 = TBL_SOURCECODE.SOURCECODE)
)
-- --------------------------------------------------------------
, cte_pledge_default as (
  SELECT PLE1.PLEDGEID
    ,PLE1.CREATED,PLE1.STARTDATE,PLE1.ENDDATE
    ,[STATUS] = IIF(RTRIM(ISNULL(PLE1.PLEDGESTATUS,''))='',@BLANK, PLE1.PLEDGESTATUS)
    ,[CAMPAIGNCODE] = IIF(RTRIM(ISNULL(PLE1.RECRUITMENTMETHOD,''))='',@BLANK, PLE1.RECRUITMENTMETHOD)
    ,[RECRUITMETHOD] = IIF(RTRIM(ISNULL(PLE1.PLEDGERECRUITEDBY,''))='',@BLANK, PLE1.PLEDGERECRUITEDBY)
    ,[DESCRIPTION] = IIF(RTRIM(ISNULL(PLE1.DESCRIPTION,''))='',@BLANK, PLE1.DESCRIPTION)
    ,[PLAN] = IIF(RTRIM(ISNULL(PLE1.PLEDGEPLAN,''))='',@BLANK, PLE1.PLEDGEPLAN)
    ,[TYPE] = IIF(RTRIM(ISNULL(PLE1.PLEDGETYPE,''))='',@BLANK, PLE1.PLEDGETYPE)
    ,[PAYMENTFREQUENCY] = IIF(RTRIM(ISNULL(PLE1.PAYMENTFREQUENCY,''))='',@BLANK, PLE1.PAYMENTFREQUENCY)
    ,[PAYMENTTYPE] = IIF(PLE1.PAYMENTTYPE IS NULL OR RTRIM(PLE1.PAYMENTTYPE)='',@BLANK, PLE1.PAYMENTTYPE)
    ,[INSTALMENTVALUE] = ISNULL(PLE1.INSTALMENTVALUE,0)
    ,PLE1.CREATEDBY
    ,PLE1.SERIALNUMBER
    ,[FULLNAME] = CONCAT(IIF(PLE1.TITLE IS NULL,'', PLE1.TITLE + ' '), IIF(PLE1.FIRSTNAME IS NULL,'', PLE1.FIRSTNAME + ' '), PLE1.KEYNAME)
  FROM
    TBL_PLEDGEHEADER PLE1
  WHERE
    (
      PLE1.CREATED BETWEEN
      DATEFROMPARTS(/*<START_YEAR>*/@FY-1/*</START_YEAR>*/,/*<START_MTH>*/7/*</START_MTH>*/,/*<START_DAY>*/1/*</START_DAY>*/)
      AND
      DATEFROMPARTS(/*<END_YEAR>*/@FY/*</END_YEAR>*/,/*<END_MTH>*/6/*</END_MTH>*/,/*<END_DAY>*/30/*</END_DAY>*/)
    )
--     AND (RTRIM(ISNULL(PLE1.EXTERNALREF,''))='') AND (RTRIM(ISNULL(PLE1.EXTERNALREFTYPE,''))='')
--     AND (PLE1.DESCRIPTION IS NULL OR PLE1.DESCRIPTION NOT LIKE '%MERCHANDISE%')

)
-- --------------------------------------------------------------
, cte_legit_pledge as (
  SELECT P1.*
    ,P2.FIRST_SOURCECODE1
    ,[SPONSORSHIP1]=IIF(P2.FIRST_SOURCECODE1 = 'TLCSPON', 'TLC',
      IIF(P2.FIRST_SOURCECODE1 = 'SACTIONP', 'ACTION PARTNER',
        IIF(P2.FIRST_SOURCECODE1 = 'SPERSON', 'PERSONAL SUPPORT',
          IIF(P2.FIRST_SOURCECODE1 = 'SCOUNTRY', 'COUNTRY SUPPORT',
            IIF(P2.FIRST_SOURCECODE1 LIKE '%SCURE%', 'CURE ONE', 'AMBIGUOUS')
          )
        )
      )
    )
    ,[SPONSORSHIP2]=IIF(P2.FIRST_SOURCECODE1 = 'TLCSPON', 'TLC',
      IIF(P2.FIRST_SOURCECODE1 = 'SACTIONP', 'ACTION PARTNER',
        IIF(P2.FIRST_SOURCECODE1 = 'SPERSON', CONCAT('PERSONAL SUPPORT',': ', UPPER(P2.FIRST_DESTINATION2)),
          IIF(P2.FIRST_SOURCECODE1 = 'SCOUNTRY', CONCAT('COUNTRY SUPPORT',': ', UPPER(P2.FIRST_DESTINATION1)),
            IIF(P2.FIRST_SOURCECODE1 LIKE '%SCURE%'
            , IIF(P2.FIRST_SOURCECODE1 LIKE '%CURE%R', 'CURE ONE RENEW', 'CURE ONE ACQUISITION')
            , 'AMBIGUOUS')
          )
        )
      )
    )
    , P2.SOURCECODES, P2.FIRST_SOURCECODE2, P2.FIRST_DESTINATION1, P2.FIRST_DESTINATION2
  FROM
    cte_pledge_default P1
    LEFT JOIN cte_pledge_sourcetype P2 ON (P1.PLEDGEID=P2.PLEDGEID)
  WHERE
    P2.SOURCETYPE LIKE '%SPONSORSHIP'
)
-- --------------------------------------------------------------
-- , cte_pledge_total as (
--   SELECT
--     TBL_BATCHITEMPLEDGE.PLEDGEID
--     ,[LTD_TOTAL] = SUM(TBL_BATCHITEMPLEDGE.PAYMENTAMOUNT)
--     ,[PAID_INSTALMENTS] = COUNT(DISTINCT TBL_BATCHITEMPLEDGE.PLEDGELINENO)
--   FROM
--     TBL_BATCHITEMPLEDGE
--     LEFT JOIN TBL_BATCHITEM ON (TBL_BATCHITEMPLEDGE.ADMITNAME = TBL_BATCHITEM.ADMITNAME AND TBL_BATCHITEMPLEDGE.RECEIPTNO = TBL_BATCHITEM.RECEIPTNO AND TBL_BATCHITEMPLEDGE.SERIALNUMBER = TBL_BATCHITEM.SERIALNUMBER)
--   WHERE
--     TBL_BATCHITEM.REVERSED IS NULL OR NOT(TBL_BATCHITEM.REVERSED=1 OR TBL_BATCHITEM.REVERSED=-1)
--   GROUP BY
--     TBL_BATCHITEMPLEDGE.PLEDGEID
-- )
, cte_pledge_total as (
  SELECT
    Tbl_PLEDGEINSTALMENTS_CLOSED.PLEDGEID
    ,[LTD_TOTAL] = SUM(Tbl_PLEDGEINSTALMENTS_CLOSED.AMOUNTPAID)
    ,[PAID_INSTALMENTS] = COUNT(DISTINCT Tbl_PLEDGEINSTALMENTS_CLOSED.INSTALMENTID)
  FROM
    Tbl_PLEDGEINSTALMENTS_CLOSED
  GROUP BY
    Tbl_PLEDGEINSTALMENTS_CLOSED.PLEDGEID
)
-- --------------------------------------------------------------
, cte_pledge_due as (
  SELECT
    DUE.PLEDGEID
    ,[FIRST_DUE] = MIN(DUE.DATEDUE)
    ,[OVERDUE] = IIF(MIN(DUE.DATEDUE) IS NULL, NULL, IIF(MIN(DUE.DATEDUE)<CAST(CURRENT_TIMESTAMP AS DATE), -1, NULL))
  FROM
    TBL_PLEDGEINSTALMENTS_ACTIVE AS DUE
  GROUP BY
    DUE.PLEDGEID
)
-- --------------------------------------------------------------
, cte_pledge as (
  SELECT P1.*
    ,P4.OVERDUE, P4.FIRST_DUE
    ,P3.LTD_TOTAL, P3.PAID_INSTALMENTS
  FROM
    cte_legit_pledge P1
    LEFT JOIN cte_pledge_total P3 ON (P1.PLEDGEID=P3.PLEDGEID)
    LEFT JOIN cte_pledge_due P4 ON (P1.PLEDGEID=P4.PLEDGEID)
)
-- --------------------------------------------------------------
select *
from cte_pledge
order by CREATED desc