select
  t1.PLEDGEID
  ,t1.CREATED ,t1.CREATEDBY
  ,t1.[PLAN] ,t1.PAYMENTTYPE ,t1.PAYMENTFREQUENCY
	,count(t2.DATEDUE) AS [DUES]
  ,cast(min(t2.DATEDUE) as date) AS [FIRSTOVERDUE]
  ,cast(max(t2.DATEDUE) as date) AS [LASTOVERDUE]
  ,t1.FIRST_SOURCECODE1
--   ,t1.SPONSORSHIP1
  ,t1.SPONSORSHIP2
--   ,t1.CAMPAIGNCODE ,t1.RECRUITMETHOD
from
  cte_legit_pledge t1
  left join TBL_PLEDGEINSTALMENTS_ACTIVE t2 on (t1.PLEDGEID = t2.PLEDGEID)
where
  t1.STATUS like '%Active%' AND t2.DATEDUE < CAST(CURRENT_TIMESTAMP AS DATE)
group by
  t1.PLEDGEID
  , t1.FIRST_SOURCECODE1
--   , t1.SPONSORSHIP1
  , t1.SPONSORSHIP2
--   , t1.CAMPAIGNCODE, t1.RECRUITMETHOD
  , t1.PAYMENTTYPE, t1.PAYMENTFREQUENCY, t1.[PLAN]
  , t1.CREATED, t1.CREATEDBY
order by
  min(t2.DATEDUE) asc