select
  t1.DATEOFPAYMENT
  ,t1.ACTUAL_TOTAL
  ,t1.ADMITNAME
  ,[PLATFORM] = IIF(t1.SOURCETYPE LIKE 'Merch%Sponsorship','Merchandise', 'Non-Merchandise')
  ,t1.ACTUAL_SCOURCE1
  ,[DEFUALT_SCOURCE1] = IIF(t1.ACTUAL_SCOURCE1=t2.FIRST_SOURCECODE1, '[SAA]', t2.FIRST_SOURCECODE1)
  ,t1.PLEDGEID,t2.CREATED,t2.STARTDATE
  ,[INSTALMENT] = t1.PLEDGELINENO
  ,t2.ACQUISITION_CAMPAIGNCODE,t2.ACQUISITION_DETAIL
  ,[SPONSORSHIP1] = ISNULL(t2.SPONSORSHIP1, '_PLEDGE MISSING')
  ,[SPONSORSHIP2] = ISNULL(t2.SPONSORSHIP2, '_PLEDGE MISSING')
  ,[SPONSORSHIP1_COLOR] = ISNULL(t2.SPONSORSHIP1_COLOR, '#464646')

from
  cte_pledge_actual t1
  left join cte_pledge t2 ON (t1.PLEDGEID=t2.PLEDGEID)
where
  DATEOFPAYMENT between /*<DOP_START>*/'20180701'/*</DOP_START>*/ and /*<DOP_END>*/'20190630'/*</DOP_END>*/
order by
  DATEOFPAYMENT desc



