DECLARE
@CAMPAIGNCODE varchar(25) = /*<CAMPAIGN_CODE>*/'19DV.Cure One Stew'/*</CAMPAIGN_CODE>*/
, @UNSOLICITED varchar(25) = '____.Unsolicited'
;
WITH
-- -------------------------------------------------------------------------------------------------------------
cte_payment as (
    SELECT
        B1.SERIALNUMBER
        , B2.DATEOFPAYMENT
        , YEAR(B2.DATEOFPAYMENT) + CASE WHEN MONTH(B2.DATEOFPAYMENT)<7 THEN 0 ELSE 1 END AS [FY]
        , B1.PAYMENTAMOUNT
        , CASE WHEN B2.REVERSED = 2 OR B2.REVERSED = 1 OR B2.REVERSED = -1 THEN 0 ELSE -1 END AS [ISTRX]
        , B1.SOURCECODE
        , CASE WHEN S1.ADDITIONALCODE3 IS NULL OR RTRIM(S1.ADDITIONALCODE3) = '' OR S1.ADDITIONALCODE3 LIKE '%Unsolicited%' THEN
            CASE WHEN S1.SOURCETYPE LIKE '%Sponsorship' THEN
              CASE WHEN P1.RECRUITMENTMETHOD IS NULL OR P1.RECRUITMENTMETHOD LIKE '%Unsolicited%' THEN @UNSOLICITED
              ELSE P1.RECRUITMENTMETHOD
              END
            ELSE @UNSOLICITED
            END
          ELSE S1.ADDITIONALCODE3
          END AS [CAMPAIGNCODE]

        , [PLEDGEID] = CASE WHEN RTRIM(B3.PLEDGEID) = '' THEN NULL ELSE B3.PLEDGEID END
        , [PLEDGETYPE] = IIF(RTRIM(B3.PLEDGEID) = '' OR B3.PLEDGEID IS NULL, NULL,
          IIF(B1.SOURCECODE = 'TLCSPON', 'TLC',
            IIF(B1.SOURCECODE IN ('SACTIONP','ACTCRA','ACTCRM'), 'ACTION PARTNER',
            IIF(B1.SOURCECODE = 'SPERSON', 'PERSONAL SUPPORT',
            IIF(B1.SOURCECODE IN ('SCOUNTRY','SPNEPAL','SPNG', 'SNIGER', 'SINDIA', 'STHAIL', 'SNIGERIA', 'SMYANM', 'SETIMOR', 'SNIGERIA', 'SCHINA', 'SCONGO'), 'COUNTRY SUPPORT',
            IIF(B1.SOURCECODE LIKE '%SCURE%' OR B1.SOURCECODE IN ('CUREONE1', 'CUREONE2'), 'CURE ONE', '_AMBIGUOUS')
            )))))

        , [TRXID] = CASE WHEN B2.REVERSED=2 THEN 0
                    ELSE DENSE_RANK() OVER(PARTITION BY (CASE WHEN B2.REVERSED=2 THEN 2 ELSE NULL END) ORDER BY CONCAT(CONVERT(VARCHAR(10), B2.DATEOFPAYMENT, 112), B2.SERIALNUMBER, B2.ADMITNAME, B2.RECEIPTNO) ASC)
                    END

    FROM
        TBL_BATCHITEMSPLIT            B1
        LEFT JOIN TBL_BATCHITEM       B2 ON (B1.SERIALNUMBER = B2.SERIALNUMBER) AND (B1.RECEIPTNO = B2.RECEIPTNO) AND (B1.ADMITNAME = B2.ADMITNAME)
        LEFT JOIN TBL_BATCHITEMPLEDGE B3 ON (B1.SERIALNUMBER = B3.SERIALNUMBER) AND (B1.RECEIPTNO = B3.RECEIPTNO) AND (B1.ADMITNAME = B3.ADMITNAME) AND (B1.LINEID = B3.LINEID)
        LEFT JOIN TBL_PLEDGEHEADER    P1 ON (B3.PLEDGEID = P1.PLEDGEID)
        LEFT JOIN TBL_BATCHHEADER     B4 ON (B2.ADMITNAME = B4.ADMITNAME)
        LEFT JOIN Tbl_SOURCECODE      S1 ON (B1.SOURCECODE = S1.SOURCECODE)
    WHERE
        (B2.REVERSED IS NULL OR NOT(B2.REVERSED IN (1, -1))) AND (B4.STAGE ='Batch Approved')
        AND ( S1.ADDITIONALCODE3 = @CAMPAIGNCODE
              OR ((S1.ADDITIONALCODE3 IS NULL OR S1.ADDITIONALCODE3 = '') AND P1.RECRUITMENTMETHOD = @CAMPAIGNCODE) )
)
-- -------------------------------------------------------------------------------------------------------------
, cte_first_date AS (
    SELECT SERIALNUMBER
        , [FIRST_DATE] = MIN(DATEOFPAYMENT)
        , [LAST_DATE] = MAX(DATEOFPAYMENT)
    FROM cte_payment
    WHERE ISTRX = -1
    GROUP BY SERIALNUMBER
)
-- -------------------------------------------------------------------------------------------------------------
, cte_contact AS (
    SELECT CT1.SERIALNUMBER
        , [FULLNAME] = CONCAT(
              CASE WHEN RTRIM(CT1.TITLE)='' OR CT1.TITLE IS NULL THEN '' ELSE RTRIM(CT1.TITLE)+' ' END
            , CASE WHEN RTRIM(CT1.FIRSTNAME)='' OR CT1.FIRSTNAME IS NULL THEN '' ELSE RTRIM(CT1.FIRSTNAME)+' ' END
            , CASE WHEN RTRIM(CT1.OTHERINITIAL)='' OR CT1.OTHERINITIAL IS NULL THEN '' ELSE RTRIM(CT1.OTHERINITIAL)+' ' END
            , CT1.KEYNAME
        )
        , [MOBILENUMBER] = CASE WHEN RTRIM(CT1.MOBILENUMBER) = '' THEN NULL ELSE RTRIM(CT1.MOBILENUMBER) END
        , [DAYTELEPHONE] = CASE WHEN RTRIM(CT1.DAYTELEPHONE) = '' THEN NULL ELSE RTRIM(CT1.DAYTELEPHONE) END
        , [EVENINGTELEPHONE] = CASE WHEN RTRIM(CT1.EVENINGTELEPHONE) = '' THEN NULL ELSE RTRIM(CT1.EVENINGTELEPHONE) END
        , CT1.EMAILADDRESS
    FROM
        TBL_CONTACT CT1
    WHERE CT1.CONTACTTYPE <> 'ADDRESS'
)
-- -------------------------------------------------------------------------------------------------------------

select * from cte_payment
