DECLARE @UNSOLICITED AS VARCHAR(15) = 'Unsolicited'
      , @SOLICITED AS VARCHAR(15) = 'Solicited'
      , @CAMPAIGNCODE_UNSOLICITED varchar(25) = '____.Unsolicited'
      ;
WITH
-- --------------------------------------------------------------
cet_mysourcecode AS (
  SELECT SOURCECODE,SOURCETYPE
    , ADDITIONALCODE1  AS [ACCOUNT]
    , ADDITIONALCODE5  AS [CLASS]
    , ADDITIONALCODE3  AS [CAMPAIGN]
  	,IIF(SOURCETYPE LIKE 'Merch%', 'Merchandise Platform','Non-Merchandise Platform') AS [PLATFORM]
  	,IIF(SOURCETYPE LIKE 'Bequest', 'Bequest'
      ,IIF(SOURCETYPE LIKE '%Sponsorship%', 'Pledge'
	    ,IIF(SOURCETYPE LIKE 'Merch%Purchase%' OR SOURCETYPE LIKE 'Merch%Postage%', 'Purchase-Postage'
	    ,IIF(SOURCETYPE LIKE 'Group', 'Group'
          ,'Donation')))) AS [TQTYPE]
  FROM TBL_SOURCECODE
)
-- --------------------------------------------------------------
,cte_sankey_attributes AS (
  SELECT
    SUM(B1.PAYMENTAMOUNT) AS TOTAL
    , [TLMA] = 'TLMA'
    , S1.PLATFORM
    , S1.TQTYPE

    , IIF(RTRIM(ISNULL(S1.CAMPAIGN,'')) = '' OR LEFT(UPPER(LTRIM(S1.CAMPAIGN)),4) = 'TLMA'
      , IIF(S1.TQTYPE = 'Pledge'
          , IIF(RTRIM(ISNULL(P1.RECRUITMENTMETHOD,''))='' OR P1.RECRUITMENTMETHOD LIKE '%Unsolicited%', @UNSOLICITED, @SOLICITED)
          , @UNSOLICITED)
      , @SOLICITED) AS [SOLICIT]

    , IIF(RTRIM(ISNULL(S1.CAMPAIGN,'')) = '' OR LEFT(UPPER(LTRIM(S1.CAMPAIGN)),4) = 'TLMA'
      , IIF(S1.TQTYPE = 'Pledge'
        , IIF(RTRIM(ISNULL(P1.RECRUITMENTMETHOD,''))='' OR P1.RECRUITMENTMETHOD LIKE '%Unsolicited%', @CAMPAIGNCODE_UNSOLICITED, P1.RECRUITMENTMETHOD)
        , @CAMPAIGNCODE_UNSOLICITED)
      , S1.CAMPAIGN) AS [CAMPAIGNCODE]

    , IIF(RTRIM(ISNULL(B2.PAYMENTTYPE,''))='','Missing PaymentType', RTRIM(B2.PAYMENTTYPE)) AS [PAYMENTTYPE]
    , ISNULL(S1.ACCOUNT, 'Missing') AS [ACCOUNT]
    , ISNULL(S1.CLASS, 'Missing') AS [CLASS]
--     , B1.SOURCECODE AS [SRC1]
    , IIF(RTRIM(ISNULL(B1.SOURCECODE2,''))='','MissingSRC2', RTRIM(B1.SOURCECODE2)) AS [SRC2]
    , IIF(RTRIM(ISNULL(B1.DESTINATIONCODE,'')) ='', 'Missing DES1', IIF(D1.ARCHIVE = -1, 'Archived1', IIF(B1.DESTINATIONCODE IN ('General','Merchandise'), 'General1',B1.DESTINATIONCODE))) AS [DES1]
    , IIF(RTRIM(ISNULL(B1.DESTINATIONCODE2,'')) ='', 'Missing DES2', IIF(D2.ARCHIVE = -1, 'Archived2', IIF(B1.DESTINATIONCODE2 IN ('General','Merchandise','DONKIND'), 'General2',B1.DESTINATIONCODE2))) AS [DES2]

  FROM
    TBL_BATCHITEMSPLIT        B1
    LEFT JOIN TBL_BATCHITEM   B2 ON (B1.SERIALNUMBER = B2.SERIALNUMBER) AND (B1.RECEIPTNO = B2.RECEIPTNO) AND (B1.ADMITNAME = B2.ADMITNAME)
    LEFT JOIN TBL_BATCHITEMPLEDGE B3 ON (B1.SERIALNUMBER = B3.SERIALNUMBER) AND (B1.RECEIPTNO = B3.RECEIPTNO) AND (B1.ADMITNAME = B3.ADMITNAME) AND (B1.LINEID = B3.LINEID)
    LEFT JOIN TBL_BATCHHEADER B4 ON (B2.ADMITNAME = B4.ADMITNAME)
    LEFT JOIN cet_mysourcecode   S1 ON (B1.SOURCECODE = S1.SOURCECODE)
    LEFT JOIN TBL_PLEDGEHEADER P1 ON (B3.PLEDGEID = P1.PLEDGEID)
    LEFT JOIN TBL_DESTINATIONCODE  D1 ON (B1.DESTINATIONCODE = D1.DESTINATIONCODE)
    LEFT JOIN TBL_DESTINATIONCODE2 D2 ON (B1.DESTINATIONCODE2 = D2.DESTINATIONCODE2)
  WHERE
    (B2.REVERSED IS NULL OR NOT(B2.REVERSED IN (1, -1))) AND (B4.STAGE ='Batch Approved')
    AND B2.DATEOFPAYMENT BETWEEN ? AND ?
  GROUP BY
    S1.PLATFORM, S1.TQTYPE, S1.ACCOUNT, S1.CAMPAIGN, S1.CLASS
    , B1.DESTINATIONCODE
    , B1.DESTINATIONCODE2
--     , B1.SOURCECODE
    , B1.SOURCECODE2
    , B2.PAYMENTTYPE
    , P1.RECRUITMENTMETHOD
    , D1.ARCHIVE, D2.ARCHIVE

)
-- --------------------------------------------------------------
select * from cte_sankey_attributes