DECLARE @UNSOLICITED AS VARCHAR(15) = 'Unsolicited'
      , @SOLICITED AS VARCHAR(15) = 'Solicited';
WITH
-- --------------------------------------------------------------
cet_mysourcecode AS (
  SELECT SOURCECODE,SOURCETYPE
    , ADDITIONALCODE1  AS [ACCOUNT]
    , ADDITIONALCODE5  AS [CLASS]
    , ADDITIONALCODE3  AS [CAMPAIGN]
  	,IIF(SOURCETYPE LIKE 'Merch%', 'Merchandise Platform','Non-Merchandise Platform') AS [PLATFORM]
  	,IIF(RTRIM(ISNULL(ADDITIONALCODE3,'')) = '' OR UPPER(LTRIM(ADDITIONALCODE3)) = 'TLMA', @UNSOLICITED, @SOLICITED) AS [SOLICIT]
  	,IIF(SOURCETYPE LIKE 'Bequest', 'Bequest'
      ,IIF(SOURCETYPE LIKE '%Sponsorship%', 'Pledge'
	    ,IIF(SOURCETYPE LIKE 'Merch%Purchase%' OR SOURCETYPE LIKE 'Merch%Postage%', 'Purchase-Postage'
	    ,IIF(SOURCETYPE LIKE 'Group', 'Group'
          ,'Donation')))) AS [TQTYPE]
  FROM TBL_SOURCECODE
)
-- --------------------------------------------------------------
,cte_sankey_attributes AS (
  SELECT
    SUM(B1.PAYMENTAMOUNT) AS TOTAL
    , [SOLICIT] = IIF(S1.TQTYPE = 'Pledge' AND S1.SOLICIT = @UNSOLICITED
        , IIF(RTRIM(ISNULL(P1.RECRUITMENTMETHOD,''))='' ,@UNSOLICITED, @SOLICITED)
        ,S1.SOLICIT)
    , S1.PLATFORM
    , S1.TQTYPE
    , S1.ACCOUNT
    , ISNULL(IIF(D1.ARCHIVE = -1, 'Archived 1', IIF(B1.DESTINATIONCODE IN ('General','Merchandise'), 'General 1',B1.DESTINATIONCODE)), 'Missing') AS [DES1]
    , ISNULL(IIF(D2.ARCHIVE = -1, 'Archived 2', IIF(B1.DESTINATIONCODE2 IN ('General','Merchandise','DONKIND'), 'General 2',B1.DESTINATIONCODE2)), 'Missing') AS [DES2]

  FROM
    TBL_BATCHITEMSPLIT        B1
    LEFT JOIN TBL_BATCHITEM   B2 ON (B1.SERIALNUMBER = B2.SERIALNUMBER) AND (B1.RECEIPTNO = B2.RECEIPTNO) AND (B1.ADMITNAME = B2.ADMITNAME)
    LEFT JOIN TBL_BATCHITEMPLEDGE B3 ON (B1.SERIALNUMBER = B3.SERIALNUMBER) AND (B1.RECEIPTNO = B3.RECEIPTNO) AND (B1.ADMITNAME = B3.ADMITNAME) AND (B1.LINEID = B3.LINEID)
    LEFT JOIN TBL_BATCHHEADER B4 ON (B2.ADMITNAME = B4.ADMITNAME)
    LEFT JOIN cet_mysourcecode   S1 ON (B1.SOURCECODE = S1.SOURCECODE)
    LEFT JOIN TBL_PLEDGEHEADER P1 ON (B3.PLEDGEID = P1.PLEDGEID)
    LEFT JOIN TBL_DESTINATIONCODE  D1 ON (B1.DESTINATIONCODE = D1.DESTINATIONCODE)
    LEFT JOIN TBL_DESTINATIONCODE2 D2 ON (B1.DESTINATIONCODE2 = D2.DESTINATIONCODE2)
  WHERE
    (B2.REVERSED IS NULL OR NOT(B2.REVERSED IN (1, -1))) AND (B4.STAGE ='Batch Approved')
    AND B2.DATEOFPAYMENT BETWEEN ? AND ?
  GROUP BY
    S1.SOLICIT ,S1.PLATFORM ,S1.TQTYPE ,B1.DESTINATIONCODE, B1.DESTINATIONCODE2 , S1.ACCOUNT
    , P1.RECRUITMENTMETHOD
    , D1.ARCHIVE, D2.ARCHIVE
)
-- --------------------------------------------------------------
select * from cte_sankey_attributes
order by TOTAL desc -- !Important for sankey chart