WITH
cte_sourcecode AS (
  SELECT
      SOURCECODE, SOURCETYPE, DESTINATIONCODE AS DDES1, DESTINATIONCODE2  AS DDES2
      ,ADDITIONALCODE3 AS CAMPAIGNCODE, ADDITIONALCODE1 AS ACCOUNT, ADDITIONALCODE5 AS CLASS
      ,SOURCESTARTDATE, CREATED, CREATEDBY, SOURCEDESCRIPTION, SOURCENOTES, EXCLUDEFROMDROPDOWN, ARCHIVE, TAXDEDUCTIBLE, GOODSTAXAPPLICABLE
  FROM TBL_SOURCECODE
)
----------------------------------------------------------------------------------------------------------------------------
select S1.*
from cte_sourcecode S1
--   left join TBL_BATCHITEMSPLIT    B1
--   left join TBL_BATCHITEM   B2 ON (B1.SERIALNUMBER = B2.SERIALNUMBER) AND (B1.RECEIPTNO = B2.RECEIPTNO) AND (B1.ADMITNAME = B2.ADMITNAME)
where S1.CREATED between ? and ?
order by S1.CREATED desc