WITH
cte_sourcecode AS (
SELECT
    SOURCECODE, SOURCETYPE, DESTINATIONCODE AS DDES1, DESTINATIONCODE2  AS DDES2
    ,ADDITIONALCODE3 AS CAMPAIGNCODE, ADDITIONALCODE1 AS ACCOUNT, ADDITIONALCODE5 AS CLASS
    ,CREATED
FROM TBL_SOURCECODE
)
----------------------------------------------------------------------------------------------------------------------------
, cte_payment AS (
SELECT

FROM
  TBL_BATCHITEMSPLIT    B1
  LEFT JOIN TBL_BATCHITEM   B2 ON (B1.SERIALNUMBER = B2.SERIALNUMBER) AND (B1.RECEIPTNO = B2.RECEIPTNO) AND (B1.ADMITNAME = B2.ADMITNAME)
  LEFT JOIN TBL_BATCHITEM   B2 ON (B1.SERIALNUMBER = B2.SERIALNUMBER) AND (B1.RECEIPTNO = B2.RECEIPTNO) AND (B1.ADMITNAME = B2.ADMITNAME)
)




select *
from cte_sourcecode
where CREATED BETWEEN DATEFROMPARTS(IIF(MONTH(CURRENT_TIMESTAMP)<7,YEAR(CURRENT_TIMESTAMP)-1,YEAR(CURRENT_TIMESTAMP)),6,1)
		  AND DATEFROMPARTS(IIF(MONTH(CURRENT_TIMESTAMP)<7,YEAR(CURRENT_TIMESTAMP),YEAR(CURRENT_TIMESTAMP)+1),6,30)